### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by arsfeld** [0xERR0R/blocky#1311]
I've been getting this error `index out of range [0] with length 0` for a few days now, I thought it was related to #1113 but I've switch to Blocky master and I'm still getting it. 

I've enabled debug logs and here's the lines i have:

```
● blocky.service - A DNS proxy and ad-blocker for the local network
     Loaded: loaded (/etc/systemd/system/blocky.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2023-12-19 16:14:18 EST; 23ms ago
    Process: 3153740 ExecStart=/nix/store/bnw1pasm25gws00zn7wvhb0iqh3phb48-blocky-git/bin/blocky --config /nix/store/mawzcmx6b7mk3qm2nybdlw1rmg61wlj4-config.yaml (code=exited, status=2)
   Main PID: 3153740 (code=exited, status=2)
         IP: 1.2M in, 212.8K out
        CPU: 2.780s

---------------------------

Dec 19 16:14:18 storage blocky[3153740]: [2023-12-19 16:14:18] DEBUG parallel_best: delegating to resolver client_ip=192.168.1.20 client_names=192.168.1.20 question=PTR (lb._dns-sd._udp.2.0.0.192.in-addr.arpa.) resolver=upstream 'tcp+udp:1.1.1.2'
Dec 19 16:14:18 storage blocky[3153740]: [2023-12-19 16:14:18]  INFO queryLog: query resolved answer= client_ip=192.168.1.20 client_names=192.168.1.20 duration_ms=0 hostname=storage question_name=lb._dns-sd._udp.0.1.168.192.in-addr.arpa. question_type=PTR response_code=NXDOMAIN response_reason=Special-Use Domain Name response_type=SPECIAL
Dec 19 16:14:18 storage blocky[3153740]: [2023-12-19 16:14:18] DEBUG rewriter_resolver: rewriting "lb._dns-sd._udp.home.lan" to "lb._dns-sd._udp.home.bat-boa.ts.net" client_ip=192.168.1.20 client_names=192.168.1.20 question=PTR (lb._dns-sd._udp.home.lan.) rewrite=lan:bat-boa.ts.net
Dec 19 16:14:18 storage blocky[3153740]: [2023-12-19 16:14:18] DEBUG parallel_best: delegating to resolver client_ip=192.168.1.20 client_names=192.168.1.20 question=PTR (lb._dns-sd._udp.home.lan.) resolver=upstream 'tcp+udp:100.100.100.100'
Dec 19 16:14:18 storage blocky[3153740]: [2023-12-19 16:14:18] DEBUG upstream: received response from upstream answer= net=tcp+udp protocol=UDP response_time_ms=0 return_code=NXDOMAIN upstream=tcp+udp:100.100.100.100 upstream_ip=100.100.100.100
Dec 19 16:14:18 storage blocky[3153740]: [2023-12-19 16:14:18] DEBUG conditional_resolver: received response from conditional upstream answer= client_ip=192.168.1.20 client_names=192.168.1.20 domain=ts.net question=PTR (lb._dns-sd._udp.home.lan.) upstream=parallel_best upstreams '<conditional in ts.net> (upstream 'tcp+udp:100.100.100.100')'
Dec 19 16:14:18 storage blocky[3153740]: panic: runtime error: index out of range [0] with length 0
Dec 19 16:14:18 storage blocky[3153740]: goroutine 1423 [running]:
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*RewriterResolver).Resolve(0xc000142280, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/rewriter_resolver.go:101 +0x639
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*CachingResolver).Resolve(0xc0002485a0, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/caching_resolver.go:192 +0x50c
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*BlockingResolver).Resolve(0xc0002d4600, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/blocking_resolver.go:407 +0xf2
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*HostsFileResolver).Resolve(0xc00056a120, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/hosts_file_resolver.go:114 +0x52a
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*CustomDNSResolver).Resolve(0xc000142240, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/custom_dns_resolver.go:144 +0x1d7
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*MetricsResolver).Resolve(0xc000248410, {0x12a0f88?, 0xc000396000?}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/metrics_resolver.go:30 +0x4b
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*QueryLoggingResolver).Resolve(0xc0001421c0, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/query_logging_resolver.go:119 +0x9c
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*EDEResolver).Resolve(0xc0002e5420?, {0x12a0f88?, 0xc000396000?}, 0xc?)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/ede_resolver.go:32 +0x74
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*ClientNamesResolver).Resolve(0xc001727c70, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/client_names_resolver.go:68 +0x1a2
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*ECSResolver).Resolve(0xc00034e7b0, {0x12a0f88, 0xc000396000}, 0x1?)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/ecs_resolver.go:73 +0x218
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*FQDNOnlyResolver).Resolve(0xc00034e780, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/fqdn_only_resolver.go:37 +0x111
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/resolver.(*FilteringResolver).Resolve(0xc00034e750, {0x12a0f88, 0xc000396000}, 0xc0002e5490)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/resolver/filtering_resolver.go:35 +0x1c4
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/server.(*Server).OnRequest(0xc000b92000, {0x12a0f88, 0xc000396000}, {0x12a8e70, 0xc000a97800}, 0xc000468990)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/server/server.go:603 +0x106
Dec 19 16:14:18 storage blocky[3153740]: github.com/0xERR0R/blocky/server.(*Server).registerDNSHandlers.func1({0x12a8e70?, 0xc000a97800?}, 0xc00007de40?)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/0xERR0R/blocky/server/server.go:420 +0x3b
Dec 19 16:14:18 storage blocky[3153740]: github.com/miekg/dns.HandlerFunc.ServeDNS(0xc00039e000?, {0x12a8e70?, 0xc000a97800?}, 0xc?)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/miekg/dns@v1.1.57/server.go:37 +0x29
Dec 19 16:14:18 storage blocky[3153740]: github.com/miekg/dns.(*ServeMux).ServeDNS(0xc000704000?, {0x12a8e70?, 0xc000a97800?}, 0xc000468990?)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/miekg/dns@v1.1.57/serve_mux.go:103 +0x6e
Dec 19 16:14:18 storage blocky[3153740]: github.com/miekg/dns.(*Server).serveDNS(0xc0003a0000, {0xc000704000, 0x2a, 0xffff}, 0xc000a97800)
Dec 19 16:14:18 storage blocky[3153740]:         github.com/miekg/dns@v1.1.57/server.go:663 +0x432
Dec 19 16:14:18 storage blocky[3153740]: github.com/miekg/dns.(*Server).serveUDPPacket(0xc0003a0000, 0xc000ae17d0?, {0xc000704000, 0x2a, 0xffff}, {0x12a6360?, 0xc0003a4000}, 0xc000955a20, {0x0, 0x0})
Dec 19 16:14:18 storage blocky[3153740]:         github.com/miekg/dns@v1.1.57/server.go:607 +0x1cc
Dec 19 16:14:18 storage blocky[3153740]: created by github.com/miekg/dns.(*Server).serveUDP in goroutine 82
Dec 19 16:14:18 storage blocky[3153740]:         github.com/miekg/dns@v1.1.57/server.go:537 +0x456
Dec 19 16:14:18 storage systemd[1]: blocky.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 19 16:14:18 storage systemd[1]: blocky.service: Failed with result 'exit-code'.
Dec 19 16:14:18 storage systemd[1]: blocky.service: Triggering OnFailure= dependencies.
Dec 19 16:14:18 storage systemd[1]: blocky.service: Consumed 2.780s CPU time, received 1.2M IP traffic, sent 212.8K IP traffic.
```

I have integrated Blocky with the tailscale resolver by using this configuration:

```nix
      conditional = {
        rewrite = {
          lan = "bat-boa.ts.net";
        };
        mapping = {
          "ts.net" = "100.100.100.100";
        };
      };
```
(it's in Nix format, I'm using Blocky in NixOS)

It seems Blocky doesn't like the output of the Tailscale resolver. I'll disable this integration for now, not even sure it's a bug in Blocky or not.

**Comment by ThinkChaos** [comment]
Hi, thanks for the thorough report and taking the time to test with the main branch.

It looks like the response doesn't have the question section which is odd since usually servers echo the question back. We definitely shouldn't be panicking though.
I'll make a PR with a fix.

**Comment by ThinkChaos** [comment]
PR is open: #1312 (nice)

I'd recommend reporting it to Tailscale too since this is pretty unusual behavior.  
I took a quick look at the spec and it seems allowed, just I don't know of any other resolvers that do this.

**Comment by kwitsch** [comment]
I agree, even if it's allowed it's very uncommon and should be reported since there are DNS clients that won't accept such answers.
