### ISSUE TITLE
Cannot start the blocky with docker-compose command

### ISSUE THREAD

**Issue by SLCCL** [0xERR0R/blocky#758]
Hello guys,
I wondering how to fix the error show as below while I'm trying to start the blocky & grafana & prometheus at once by "docker-compose up -d". 

Error Message:
"
@raspberrypi:~ $ docker-compose up -d
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 13, in <module>
    import docker.errors
ModuleNotFoundError: No module named 'docker.errors'
"

After spending some time of searching on the internet, I've no idea what's wrong with it. 
*docker start normally and all the docker-compose command show the same result above*
Any help would be very appreciated! Thanks!

**Comment by kwitsch** [comment]
Looks like your compose installation is broken.

I'm guessing you run this on raspberry pi os, am I right?
If so, which installation variant did you use?
And have you tried using the [offical repo](https://docs.docker.com/engine/install/debian/#install-using-the-repository) with the [compose plugin](https://docs.docker.com/compose/install/linux/)?

**Comment by SLCCL** [comment]
> Looks like your compose installation is broken.
> 
> I'm guessing you run this on raspberry pi os, am I right? If so, which installation variant did you use? And have you tried using the [offical repo](https://docs.docker.com/engine/install/debian/#install-using-the-repository) with the [compose plugin](https://docs.docker.com/compose/install/linux/)?

Yes，you are correct!
What is  installation variant means?  Install method? 
I just search "docker-compose raspberry pi install" on the browser and try the most fit result "sudo pip install docker-compose".

**Comment by kwitsch** [comment]
If you reinstall docker following the guide in the link above you should get a working docker compose command.
Only difference will be that it's `docker compose` instead of `docker-compose`.

**Comment by 0xERR0R** [comment]
I installed docker-compose on raspbian just with `sudo apt-get install docker-compose`. Can you try this approach (maybe you should remove your python installation of docker-compose first)?

**Comment by SLCCL** [comment]
> I installed docker-compose on raspbian just with `sudo apt-get install docker-compose`. Can you try this approach (maybe you should remove your python installation of docker-compose first)?


I've tried uninstall docker-compose with pip and use your way to install docker-compose.
The error message so much longer. Thanks for reply anyway! 

***
@raspberrypi:~ $ docker-compose up -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 18, in <module>
    import docker
  File "/usr/lib/python3/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/lib/python3/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/lib/python3/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/lib/python3/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/lib/python3/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/lib/python3/dist-packages/docker/transport/__init__.py", line 11, in <module>
    from .sshconn import SSHHTTPAdapter
  File "/usr/lib/python3/dist-packages/docker/transport/sshconn.py", line 1, in <module>
    import paramiko
  File "/usr/local/lib/python3.9/dist-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python3.9/dist-packages/paramiko/transport.py", line 40, in <module>
    from paramiko.channel import Channel
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 918, in get_code
  File "<frozen importlib._bootstrap_external>", line 587, in _compile_bytecode
ValueError: could not convert string to float: '
   " $  Rmtern @ suving rEr`�sentation0ofthI3 mjngcu,!fot febuggynw.
 ( '
*****

**Comment by SLCCL** [comment]
> Looks like your compose installation is broken.
> 
> I'm guessing you run this on raspberry pi os, am I right? If so, which installation variant did you use? And have you tried using the [offical repo](https://docs.docker.com/engine/install/debian/#install-using-the-repository) with the [compose plugin](https://docs.docker.com/compose/install/linux/)?

compose plugin from docker works perfect! Thank you so much.
Furthermore, may I know
1. What is the differences between 'docker compose' and 'docker-compose'? 
2. Would blacklist entries total =240k is too much?

Sorry for being verbose.

**Comment by 0xERR0R** [comment]
docker-compose is a separate tool (written in python) which was developed a long time ago. The tool has become so popular that it has practically become the standard. Later, the developers of docker integrated the functionality into the "docker" tool.

Regarding the list size: it depends on your system and free memory. I run blocky as docker on a raspberry pi3 with 324K blacklist entries and it needs 50MB RAM.

**Comment by SLCCL** [comment]
> docker-compose is a separate tool (written in python) which was developed a long time ago. The tool has become so popular that it has practically become the standard. Later, the developers of docker integrated the functionality into the "docker" tool.
> 
> Regarding the list size: it depends on your system and free memory. I run blocky as docker on a raspberry pi3 with 324K blacklist entries and it needs 50MB RAM.

Got it. Thanks again for all of your reply. Have a great day!  Cheers
