### ISSUE TITLE
Error after upgrading to 0.9

### ISSUE THREAD

**Issue by blackjid** [0xERR0R/blocky#87]
Hi!, 

I just upgraded to 0.9 and my blocky instance is crashing.

This are the logs
```
 [2020-07-08 11:22:48] DEBUG server: new request
 [2020-07-08 11:22:48] DEBUG blacklist_resolver: checking groups for request client_ip=10.2.0.100 client_names=black-mac.lan groupsToCheck=ads question
 [2020-07-08 11:22:48] DEBUG caching_resolver: not in cache: go to next resolver client_ip=10.2.0.100 client_names=black-mac.lan domain=notify.adobe.io
 [2020-07-08 11:22:48] DEBUG parallel_best_resolver: using upstream 'tcp+udp:8.8.4.4:53' and upstream 'tcp-tls:1.0.0.1:853' as resolver client_ip=10.2.
 [2020-07-08 11:22:48] DEBUG parallel_best_resolver: delegating to resolver client_ip=10.2.0.100 client_names=black-mac.lan question=A (notify.adobe.io
 [2020-07-08 11:22:48] DEBUG parallel_best_resolver: delegating to resolver client_ip=10.2.0.100 client_names=black-mac.lan question=A (notify.adobe.io
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7a7097]
 goroutine 536 [running]:
 github.com/miekg/dns.(*Client).Exchange(0x0, 0xc0000f3200, 0xc000596ff0, 0xb, 0x0, 0x5000104, 0x0, 0xffffffffffffffff)
     /go/pkg/mod/github.com/miekg/dns@v1.1.29/client.go:128 +0x37
 blocky/resolver.(*dnsUpstreamClient).callExternal(0xc000f1d880, 0xc0000f3200, 0xc000596ff0, 0xb, 0xc00121be01, 0x0, 0x0, 0x0, 0x0)
     /src/resolver/upstream_resolver.go:134 +0x178
 blocky/resolver.(*UpstreamResolver).Resolve(0xc000188a40, 0xc000071020, 0x5f05e494, 0xc0000afc20, 0xc001bab0d8)
     /src/resolver/upstream_resolver.go:164 +0x223
 blocky/resolver.resolve(0xc000071020, 0xc000030ff0, 0xc000071200)
     /src/resolver/parallel_best_resolver.go:127 +0x41
 created by blocky/resolver.(*ParallelBestResolver).Resolve
     /src/resolver/parallel_best_resolver.go:72 +0x4e3
```

Any idea?

**Comment by 0xERR0R** [comment]
Thanks for reporting. The bug was introduced with #67
